name: Deploy React App to Azure Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.0'

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      env:
        CI: false
      run: npm run build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ./build

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: ~

    - name: Deploy to Azure Blob Storage DEV
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob delete-batch \
            --source '$web' \
            --blob-endpoint "${{ secrets.AZURE_STORAGE_ACCOUNT_URL }}" \
            --sas-token "${{ secrets.AZURE_STORAGE_SAS_TOKEN }}"

          az storage blob upload-batch \
            --source ./build \
            --destination '$web' \
            --blob-endpoint "${{ secrets.AZURE_STORAGE_ACCOUNT_URL }}" \
            --sas-token "${{ secrets.AZURE_STORAGE_SAS_TOKEN }}"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod
    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Deploy to Azure Blob Storage PROD
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob delete-batch \
            --source '$web' \
            --blob-endpoint "${{ secrets.AZURE_STORAGE_ACCOUNT_URL_PROD }}" \
            --sas-token "${{ secrets.AZURE_STORAGE_SAS_TOKEN_PROD }}"

          az storage blob upload-batch \
            --source ./build \
            --destination '$web' \
            --blob-endpoint "${{ secrets.AZURE_STORAGE_ACCOUNT_URL_PROD }}" \
            --sas-token "${{ secrets.AZURE_STORAGE_SAS_TOKEN_PROD }}"
